name: Node React

on:
  push:
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Greeting

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Testing
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
