name: Continuous Integration

on:
  push:
  pull_request:
    branches:
    - master

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present

  deploy:
    runs-on: ubuntu-latest
    needs: buildAndTest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Testing
      - run: echo $(echo $GITHUB_REF | cut -d'/' -f 3)
