name: Continuous Integration

on:
  push:
  pull_request:
    branches:
    - master

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install
    - name: lint
      run: npm run eslint
    - name: build
      run: npm run build
    - name: e2e tests
      uses: cypress-io/github-action@v2
      with:
        command: npm run test:e2e
        start: npm start
        wait-on: 'http://localhost:3000'
        config: baseUrl=http://localhost:3000

  deploy:
    if: success() && github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest
    needs: buildAndTest
    steps:
      - uses: actions/checkout@v2
      - run: echo $(echo $GITHUB_REF | cut -d'/' -f 3)
