name: Continuous Integration

on: [push]

jobs:
  buildAndLint:
    name: Build and Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install
    - name: lint
      run: npm run eslint
    - name: build
      run: npm run build

  deploy:
    if: success() && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: buildAndLint
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: npm run build
      - uses: akhileshns/heroku-deploy@v3.11.10
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "ja-galleria-2"
          heroku_email: "airaksinen.jouni@gmail.com"
