name: Continuous Integration

on:
  push:
  pull_request:
    branches:
    - master

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present

  update-cms-master:
    name: Merge master into release after a PR is merged
    runs-on: ubuntu-latest
    needs: buildAndTest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge me!
        uses: ridedott/merge-me-action@v1
      - run: echo "Merging to master" 

  deploy:
    if: success() && github.ref == 'refs/heads/master'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: echo $(echo $GITHUB_REF | cut -d'/' -f 3)
