name: Node React

on:
  push:
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Greeting

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
